version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: afriqhome
      POSTGRES_USER: afriqhome
      POSTGRES_PASSWORD: afriqhome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: ${BACKEND_IMAGE}
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=afriqhome
      - DB_USER=afriqhome
      - DB_PASSWORD=afriqhome
      - PORT=5000
      - DATABASE_URL=postgresql://afriqhome:afriqhome@postgres:5432/afriqhome
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: ${FRONTEND_IMAGE}
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 