version: '3.8'

services:
  app:
    image: property-listing:latest
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=5000
    networks:
      - app-network
    restart: always
    depends_on:
      - db-setup

  db-setup:
    image: property-listing:latest
    command: sh -c 'sleep 10 && node /app/scripts/db-setup.js'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 